import 'package:XLcarez/env/appexports.dart';

class DisclaimerView extends StatefulWidget {
  const DisclaimerView({super.key});

  @override
  State<DisclaimerView> createState() => _DisclaimerViewState();
}

class _DisclaimerViewState extends State<DisclaimerView> {
  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return MyThemeGradient(
      child: Scaffold(
        appBar: Themeappbar(
          title: fetchlocale(context).desclaimer,
          leading: true,
        ),
        //backgroundColor: bgClr2,
        body: SafeArea(
          child: Container(
            padding: const EdgeInsets.all(10),
            margin: const EdgeInsets.all(5),
            height: size.height,
            width: size.width,
            child: SingleChildScrollView(
              child: Column(
                children: [
                  Card(
                      color: fillcor,
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Apptextwidget(fetchlocale(context).desclaimer,
                                style: TxtStls.stl20),
                            const SizedBox(height: 10),
                            Apptextwidget("""
${fetchlocale(context).theappuses}

${fetchlocale(context).instructfor}
${fetchlocale(context).ensurethelight}
${fetchlocale(context).avoidbright}
${fetchlocale(context).positionyourself}
${fetchlocale(context).keepyourface}
""",
                                //"The XLcarez app is based on the Binah.ai framework, utilizing Mean Absolute Error (MAE) and Root Mean Square Error (RMSE) as key error factors in the interpretation of test results. All outcomes generated by the app are based on AI algorithms and should not be considered definitive. Clinical diagnosis and consultation with a healthcare professional are essential for accurate health assessments. XLcarez cannot be held responsible, directly or indirectly, for any adverse effects resulting from the test results provided by this app.",
                                style: TxtStls.stl14),
                          ],
                        ),
                      )),
                  // const SizedBox(height: 10),
                  // Card(
                  //     color: fillcor,
                  //     child: Padding(
                  //       padding: const EdgeInsets.all(8.0),
                  //       child: Image.asset("assets/scan_instruction.png",),
                  // child: Column(
                  //   crossAxisAlignment: CrossAxisAlignment.start,
                  //   children: [
                  //     Apptextwidget("Scanning Instructions",
                  //         style: TxtStls.stl20),
                  //     const SizedBox(height: 10),
                  //     Apptextwidget(
                  //         "Based on the lighting conditions and the environment of the scanning area, you will have to choose the best mode of scanning.",
                  //         style: TxtStls.stl14),
                  //     const SizedBox(height: 5),
                  //     Apptextwidget("Facial Scanning (Front Camera)",
                  //         style: TxtStls.stl16),
                  //     const SizedBox(height: 5),
                  //     Apptextwidget(
                  //         "Use this mode if the room has good, consistent lighting. The front camera is used to take the scan, so you will have to hold the device steady and have it pointed at the participant in such a way that their face is inside the oval at all times during the scan. Facial symmetry analysis will be done if this method of scanning is used.",
                  //         style: TxtStls.stl14),
                  //   ],
                  // ),
                  //)),

                  //   GestureDetector(
                  //   onTap: (){
                  //     Navigator.pop(context);
                  //   },
                  //   child: Container(
                  //     margin: const EdgeInsets.only(bottom: 10,right: 10),
                  //     height: 50,
                  //     width: 100,
                  //     decoration: BoxDecoration(color: primary,border: Border.all(color: primary,width: 2),borderRadius: BorderRadius.circular(20)),
                  //     child: Center(child: Text("Skip",style:TxtStls.wstl13)),
                  //   ),
                  // ),
                  // const SizedBox(height: 10),
                ],
              ),
            ),
          ),
        ),
        bottomNavigationBar: bottomContainer(
          child: fillButton(context, load: false, title: fetchlocale(context).iuderstand,
              onTap: () {
            navigationSlide(context, const ScanningInstructionView(),
                x: 0.0, y: 1.0);
          }),
        ),
      ),
    );
  }
}
