#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef BIOSENSESIGNAL_SWIFT_H
#define BIOSENSESIGNAL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#import <BiosenseSignal/BiosenseSignal.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BiosenseSignal",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM_NAMED(NSInteger, BIOASCVDRiskLevel, "ASCVDRiskLevel", open) {
  BIOASCVDRiskLevelUnknown = 0,
  BIOASCVDRiskLevelLow = 1,
  BIOASCVDRiskLevelMedium = 2,
  BIOASCVDRiskLevelHigh = 3,
};



SWIFT_CLASS_NAMED("AccelerometerData")
@interface BIOAccelerometerData : NSObject
@property (nonatomic, readonly) double timestamp;
@property (nonatomic, readonly) int32_t x;
@property (nonatomic, readonly) int32_t y;
@property (nonatomic, readonly) int32_t z;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("AlertCodes")
@interface BIOAlertCodes : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger deviceLowPowerModeEnabledError;)
+ (NSInteger)deviceLowPowerModeEnabledError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger deviceMinimumBatteryLevelError;)
+ (NSInteger)deviceMinimumBatteryLevelError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger deviceClockSkewError;)
+ (NSInteger)deviceClockSkewError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger deviceBluetoothIsOffError;)
+ (NSInteger)deviceBluetoothIsOffError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger deviceBluetoothMissingPermissionsError;)
+ (NSInteger)deviceBluetoothMissingPermissionsError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger deviceLocationIsOffError;)
+ (NSInteger)deviceLocationIsOffError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger cameraNoCameraError;)
+ (NSInteger)cameraNoCameraError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger cameraCameraOpenError;)
+ (NSInteger)cameraCameraOpenError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger cameraCameraMissingPermissionsError;)
+ (NSInteger)cameraCameraMissingPermissionsError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger cameraUnexpectedImageDimensionsWarning;)
+ (NSInteger)cameraUnexpectedImageDimensionsWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseActivationLimitReachedError;)
+ (NSInteger)licenseActivationLimitReachedError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseMeterAttributeUsesLimitReachedError;)
+ (NSInteger)licenseMeterAttributeUsesLimitReachedError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseAuthenticationFailedError;)
+ (NSInteger)licenseAuthenticationFailedError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseInvalidLicenseKeyError;)
+ (NSInteger)licenseInvalidLicenseKeyError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseRevokedLicenseError;)
+ (NSInteger)licenseRevokedLicenseError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseInternalError9;)
+ (NSInteger)licenseInternalError9 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseLicenseExpiredError;)
+ (NSInteger)licenseLicenseExpiredError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseLicenseSuspendedError;)
+ (NSInteger)licenseLicenseSuspendedError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseNetworkIssuesError;)
+ (NSInteger)licenseNetworkIssuesError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseSslHandshakeError;)
+ (NSInteger)licenseSslHandshakeError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseInputLicenseKeyEmptyError;)
+ (NSInteger)licenseInputLicenseKeyEmptyError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseInputProductIdIllegalError;)
+ (NSInteger)licenseInputProductIdIllegalError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseCannotOpenFileForReadError;)
+ (NSInteger)licenseCannotOpenFileForReadError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseMonthlyUsageTrackingRequiresSyncError;)
+ (NSInteger)licenseMonthlyUsageTrackingRequiresSyncError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseSslHandshakeDeviceDateError;)
+ (NSInteger)licenseSslHandshakeDeviceDateError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseSslHandshakeCertificateExpiredError;)
+ (NSInteger)licenseSslHandshakeCertificateExpiredError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseMinSdkError;)
+ (NSInteger)licenseMinSdkError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseNetworkTimeoutError;)
+ (NSInteger)licenseNetworkTimeoutError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseMonitoringDisabledError;)
+ (NSInteger)licenseMonitoringDisabledError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementMisdetectionDurationExceedsLimitError;)
+ (NSInteger)measurementMisdetectionDurationExceedsLimitError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementInvalidRecentDetectionRateError;)
+ (NSInteger)measurementInvalidRecentDetectionRateError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementLicenseActivationFailedError;)
+ (NSInteger)measurementLicenseActivationFailedError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementInvalidMeasurementAverageDetectionRateError;)
+ (NSInteger)measurementInvalidMeasurementAverageDetectionRateError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementTooManyFramesInorderError;)
+ (NSInteger)measurementTooManyFramesInorderError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementMisdetectionDurationExceedsLimitWarning;)
+ (NSInteger)measurementMisdetectionDurationExceedsLimitWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementInvalidRecentFPSRateWarning;)
+ (NSInteger)measurementInvalidRecentFPSRateWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger measurementMeasurementMisplacedFrameWarning;)
+ (NSInteger)measurementMeasurementMisplacedFrameWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger vitalSignBloodPressureProcessingFailedWarning;)
+ (NSInteger)vitalSignBloodPressureProcessingFailedWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger vitalSignMeasuringWithNoEnabledVitalSignsWarning;)
+ (NSInteger)vitalSignMeasuringWithNoEnabledVitalSignsWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger sessionIllegalStartCallError;)
+ (NSInteger)sessionIllegalStartCallError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger sessionIllegalStopCallError;)
+ (NSInteger)sessionIllegalStopCallError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationInvalidProcessingTimeError;)
+ (NSInteger)initializationInvalidProcessingTimeError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationRotationAndOrientationMismatch;)
+ (NSInteger)initializationRotationAndOrientationMismatch SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationInvalidLicenseFormat;)
+ (NSInteger)initializationInvalidLicenseFormat SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationSdkLoadFailure;)
+ (NSInteger)initializationSdkLoadFailure SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationUnsupportedUserWeight;)
+ (NSInteger)initializationUnsupportedUserWeight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationUnsupportedUserAge;)
+ (NSInteger)initializationUnsupportedUserAge SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationConcurrentSessionsError;)
+ (NSInteger)initializationConcurrentSessionsError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationMissingPolarDependenciesError;)
+ (NSInteger)initializationMissingPolarDependenciesError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationMissingAnalyticsDependenciesError;)
+ (NSInteger)initializationMissingAnalyticsDependenciesError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger initializationUnsupportedUserHeight;)
+ (NSInteger)initializationUnsupportedUserHeight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceConnectionTimeoutError;)
+ (NSInteger)ppgDeviceConnectionTimeoutError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceInvalidDeviceIdError;)
+ (NSInteger)ppgDeviceInvalidDeviceIdError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceUnsupportedFirmwareVersionError;)
+ (NSInteger)ppgDeviceUnsupportedFirmwareVersionError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceUnsupportedDeviceModelError;)
+ (NSInteger)ppgDeviceUnsupportedDeviceModelError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceConnectionError;)
+ (NSInteger)ppgDeviceConnectionError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceMisplacementError;)
+ (NSInteger)ppgDeviceMisplacementError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ppgDeviceNotOnBodyWarning;)
+ (NSInteger)ppgDeviceNotOnBodyWarning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger monitoringStoppedError;)
+ (NSInteger)monitoringStoppedError SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger monitoringDataGapExceedsLimitWarning;)
+ (NSInteger)monitoringDataGapExceedsLimitWarning SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_PROTOCOL_NAMED("AlertData")
@protocol BIOAlertData
@property (nonatomic, readonly, copy) NSString * _Nonnull domain;
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull additionalInfo;
@end


SWIFT_CLASS("_TtC14BiosenseSignal12AlertDomains")
@interface AlertDomains : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull device;)
+ (NSString * _Nonnull)device SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull camera;)
+ (NSString * _Nonnull)camera SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull license;)
+ (NSString * _Nonnull)license SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull measurement;)
+ (NSString * _Nonnull)measurement SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull vitalSigns;)
+ (NSString * _Nonnull)vitalSigns SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull recorder;)
+ (NSString * _Nonnull)recorder SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull session;)
+ (NSString * _Nonnull)session SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull initialization;)
+ (NSString * _Nonnull)initialization SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ppgDevice;)
+ (NSString * _Nonnull)ppgDevice SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull monitoring;)
+ (NSString * _Nonnull)monitoring SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull all;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("BloodPressure")
@interface BIOBloodPressure : NSObject
@property (nonatomic, readonly) NSInteger systolic;
@property (nonatomic, readonly) NSInteger diastolic;
- (nonnull instancetype)initWithSystolic:(NSInteger)systolic diastolic:(NSInteger)diastolic OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOCameraLocation, "CameraLocation", open) {
  BIOCameraLocationFront = 0,
  BIOCameraLocationBack = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOConfidenceLevel, "ConfidenceLevel", open) {
  BIOConfidenceLevelUnknown = 0,
  BIOConfidenceLevelLow = 1,
  BIOConfidenceLevelMedium = 2,
  BIOConfidenceLevelHigh = 3,
};

@class BIOLicenseMessage;

SWIFT_PROTOCOL_NAMED("CoreLicenseMessageDelegate")
@protocol BIOCoreLicenseMessageDelegate
- (void)licenseMessage:(BIOLicenseMessage * _Nonnull)licenseMessage;
@end

enum BIOCoreMessageType : NSInteger;

SWIFT_CLASS_NAMED("CoreMessage")
@interface BIOCoreMessage : NSObject
@property (nonatomic, readonly) enum BIOCoreMessageType type;
@property (nonatomic, readonly) id _Nonnull value;
- (nonnull instancetype)initWithType:(enum BIOCoreMessageType)type value:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOCoreMessage (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_PROTOCOL_NAMED("CoreMessageDelegate")
@protocol BIOCoreMessageDelegate
- (void)coreMessage:(BIOCoreMessage * _Nonnull)coreMessage;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOCoreMessageType, "CoreMessageType", open) {
  BIOCoreMessageTypePulseRate = 0,
  BIOCoreMessageTypeRespirationRate = 1,
  BIOCoreMessageTypeOxygenSaturation = 2,
  BIOCoreMessageTypeBloodPressure = 3,
  BIOCoreMessageTypeError = 4,
  BIOCoreMessageTypeWarning = 5,
  BIOCoreMessageTypeReset = 6,
  BIOCoreMessageTypeDone = 7,
  BIOCoreMessageTypeSnr = 8,
  BIOCoreMessageTypePai = 9,
  BIOCoreMessageTypeAmbience = 10,
  BIOCoreMessageTypeFallDetection = 11,
  BIOCoreMessageTypeActivityLevel = 12,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIODeviceOrientation, "DeviceOrientation", open) {
  BIODeviceOrientationPortrait = 0,
  BIODeviceOrientationPortraitUpsideDown = 1,
  BIODeviceOrientationLandscapeLeft = 2,
  BIODeviceOrientationLandscapeRight = 3,
};


SWIFT_CLASS_NAMED("EnabledVitalSigns")
@interface BIOEnabledVitalSigns : NSObject
@property (nonatomic, readonly) BIOVitalSignType enabledVitalSigns;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEnabledVitalSigns:(BIOVitalSignType)enabledVitalSigns OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithVitalSignsTypes:(NSArray<NSNumber *> * _Nonnull)vitalSignsTypes OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEnabledWithVitalSignType:(BIOVitalSignType)vitalSignType SWIFT_WARN_UNUSED_RESULT;
@end


@interface BIOEnabledVitalSigns (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("ErrorData")
@interface BIOErrorData : NSObject <BIOAlertData>
@property (nonatomic, copy) NSString * _Nonnull domain;
@property (nonatomic) NSInteger code;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("FaceAngles")
@interface BIOFaceAngles : NSObject
@property (nonatomic, readonly) float yaw;
@property (nonatomic, readonly) float roll;
@property (nonatomic, readonly) float pitch;
- (nonnull instancetype)initWithYaw:(float)yaw roll:(float)roll pitch:(float)pitch OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOFaceAngles (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end

@protocol BIOSessionInfoListener;
@protocol BIOVitalSignsListener;
@protocol BIOImageListener;
@protocol BIOLogsListener;
@class BIOLicenseDetails;
enum BIOImageFormatMode : NSInteger;
@class BIOLogsConfiguration;
@protocol BIOSession;

SWIFT_CLASS_NAMED("SessionBuilder")
@interface BIOSessionBuilder : NSObject
@property (nonatomic, readonly) enum BIOCameraLocation cameraLocation;
@property (nonatomic, readonly, weak) id <BIOSessionInfoListener> _Nullable sessionInfoListener;
@property (nonatomic, readonly, weak) id <BIOVitalSignsListener> _Nullable vitalSignsListener;
@property (nonatomic, readonly, weak) id <BIOImageListener> _Nullable imageListener;
@property (nonatomic, readonly, weak) id <BIOLogsListener> _Nullable logsListener;
@property (nonatomic, readonly) BOOL detectionAlwaysOn;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable options;
@property (nonatomic, readonly, strong) BIOLicenseDetails * _Nonnull licenseDetails;
@property (nonatomic, readonly) enum BIOImageFormatMode imageFormatMode;
@property (nonatomic, readonly) BOOL strictMeasurementGuidance;
@property (nonatomic, readonly) BOOL analyticsEnabled;
@property (nonatomic, readonly, strong) BIOLogsConfiguration * _Nullable logsConfiguration;
- (id <BIOSession> _Nullable)buildWithLicenseDetails:(BIOLicenseDetails * _Nonnull)licenseDetails error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BIOSessionBuilder * _Nonnull)withSessionInfoListener:(id <BIOSessionInfoListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (BIOSessionBuilder * _Nonnull)withVitalSignsListener:(id <BIOVitalSignsListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (BIOSessionBuilder * _Nonnull)withImageListener:(id <BIOImageListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (BIOSessionBuilder * _Nonnull)withOptionsWithOptions:(NSDictionary<NSString *, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BIOSessionBuilder * _Nonnull)withAnalytics SWIFT_WARN_UNUSED_RESULT;
- (BIOSessionBuilder * _Nonnull)withLogsConfiguration:(BIOLogsConfiguration * _Nonnull)configuration listener:(id <BIOLogsListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BIOUserInformation;
@class BIOSubjectDemographic;

SWIFT_CLASS_NAMED("FaceSessionBuilder")
@interface BIOFaceSessionBuilder : BIOSessionBuilder
@property (nonatomic, readonly, strong) BIOUserInformation * _Nullable userInformation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (BIOFaceSessionBuilder * _Nonnull)withDetectionAlwaysOn:(BOOL)detectionOn SWIFT_WARN_UNUSED_RESULT;
- (BIOFaceSessionBuilder * _Nonnull)withDeviceOrientation:(enum BIODeviceOrientation)orientation SWIFT_WARN_UNUSED_RESULT;
- (BIOFaceSessionBuilder * _Nonnull)withSubjectDemographic:(BIOSubjectDemographic * _Nonnull)demographic SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use `withUserInformation()` instead.");
- (BIOFaceSessionBuilder * _Nonnull)withUserInformation:(BIOUserInformation * _Nonnull)userInformation SWIFT_WARN_UNUSED_RESULT;
- (BIOFaceSessionBuilder * _Nonnull)withImageFormatMode:(enum BIOImageFormatMode)imageFormatMode SWIFT_WARN_UNUSED_RESULT;
- (BIOFaceSessionBuilder * _Nonnull)withStrictMeasurementGuidance:(BOOL)strictMeasurementGuidance SWIFT_WARN_UNUSED_RESULT;
- (BIOFaceSessionBuilder * _Nonnull)withCameraLocation:(enum BIOCameraLocation)cameraLocation SWIFT_WARN_UNUSED_RESULT;
- (id <BIOSession> _Nullable)buildWithLicenseDetails:(BIOLicenseDetails * _Nonnull)licenseDetails error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

@class NSDate;

SWIFT_CLASS_NAMED("FallDetectionData")
@interface BIOFallDetectionData : NSObject
@property (nonatomic, readonly, copy) NSDate * _Nonnull time;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("FallDetectionListener")
@protocol BIOFallDetectionListener
- (void)onFallDetectionData:(BIOFallDetectionData * _Nonnull)fallDetectionData;
@end



SWIFT_CLASS_NAMED("GyroscopeData")
@interface BIOGyroscopeData : NSObject
@property (nonatomic, readonly) double timestamp;
@property (nonatomic, readonly) float x;
@property (nonatomic, readonly) float y;
@property (nonatomic, readonly) float z;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOHighBloodPressureRisk, "HighBloodPressureRisk", open) {
  BIOHighBloodPressureRiskUnknown = 0,
  BIOHighBloodPressureRiskLow = 1,
  BIOHighBloodPressureRiskMedium = 2,
  BIOHighBloodPressureRiskHigh = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOHighFastingGlucoseRisk, "HighFastingGlucoseRisk", open) {
  BIOHighFastingGlucoseRiskUnknown = 0,
  BIOHighFastingGlucoseRiskLow = 1,
  BIOHighFastingGlucoseRiskMedium = 2,
  BIOHighFastingGlucoseRiskHigh = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOHighHemoglobinA1CRisk, "HighHemoglobinA1CRisk", open) {
  BIOHighHemoglobinA1CRiskUnknown = 0,
  BIOHighHemoglobinA1CRiskLow = 1,
  BIOHighHemoglobinA1CRiskMedium = 2,
  BIOHighHemoglobinA1CRiskHigh = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOHighTotalCholesterolRisk, "HighTotalCholesterolRisk", open) {
  BIOHighTotalCholesterolRiskUnknown = 0,
  BIOHighTotalCholesterolRiskLow = 1,
  BIOHighTotalCholesterolRiskMedium = 2,
  BIOHighTotalCholesterolRiskHigh = 3,
};

@class UIImage;

SWIFT_CLASS_NAMED("ImageData")
@interface BIOImageData : NSObject
@property (nonatomic, readonly, strong) UIImage * _Nonnull image;
@property (nonatomic, readonly) CGRect roi;
@property (nonatomic, readonly) NSInteger imageValidity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOImageFormatMode, "ImageFormatMode", open) {
  BIOImageFormatModeStandardQuality = 0,
  BIOImageFormatModeHighQuality = 1,
};


SWIFT_PROTOCOL_NAMED("ImageListener")
@protocol BIOImageListener
- (void)onImageWithImageData:(BIOImageData * _Nonnull)imageData;
@end


SWIFT_CLASS_NAMED("ImageValidity")
@interface BIOImageValidity : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger valid;)
+ (NSInteger)valid SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger invalidDeviceOrientation;)
+ (NSInteger)invalidDeviceOrientation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger invalidRoi;)
+ (NSInteger)invalidRoi SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger tiltedHead;)
+ (NSInteger)tiltedHead SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger faceTooFar;)
+ (NSInteger)faceTooFar SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger unevenLight;)
+ (NSInteger)unevenLight SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("LicenseActivationInfo")
@interface BIOLicenseActivationInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull activationID;
- (nonnull instancetype)initWithActivationID:(NSString * _Nonnull)activationID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LicenseAuthenticationData")
@interface BIOLicenseAuthenticationData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull licenseKey;
@property (nonatomic, readonly, copy) NSString * _Nullable productID;
@property (nonatomic, readonly, copy) NSString * _Nonnull fingerprint;
@property (nonatomic, readonly, copy) NSString * _Nonnull userHash;
@property (nonatomic, readonly, copy) NSString * _Nonnull hostname;
@property (nonatomic, readonly, copy) NSString * _Nonnull appID;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOLicenseAuthenticationData (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("LicenseDetails")
@interface BIOLicenseDetails : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull licenseKey;
@property (nonatomic, readonly, copy) NSString * _Nullable productId;
- (nonnull instancetype)initWithLicenseKey:(NSString * _Nonnull)licenseKey productId:(NSString * _Nullable)productId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLicenseKey:(NSString * _Nonnull)licenseKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BIOLicenseOfflineMeasurements;

SWIFT_CLASS_NAMED("LicenseInfo")
@interface BIOLicenseInfo : NSObject
@property (nonatomic, readonly, strong) BIOLicenseActivationInfo * _Nonnull licenseActivationInfo;
@property (nonatomic, readonly, strong) BIOLicenseOfflineMeasurements * _Nullable licenseOfflineMeasurements;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LicenseMessage")
@interface BIOLicenseMessage : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger error;)
+ (NSInteger)error SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger warning;)
+ (NSInteger)warning SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger licenseData;)
+ (NSInteger)licenseData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger done;)
+ (NSInteger)done SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithType:(NSInteger)type value:(id _Nullable)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOLicenseMessage (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("LicenseOfflineMeasurements")
@interface BIOLicenseOfflineMeasurements : NSObject
@property (nonatomic, readonly) int64_t totalMeasurements;
@property (nonatomic, readonly) int64_t remainingMeasurements;
@property (nonatomic, readonly) int64_t measurementEndTimestamp;
- (nonnull instancetype)initWithTotalMeasurements:(int64_t)totalMeasurements remainingMeasurements:(int64_t)remainingMeasurements measurementEndTimestamp:(int64_t)measurementEndTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LicenseTokenData")
@interface BIOLicenseTokenData : NSObject
- (nonnull instancetype)initWithActivationID:(NSString * _Nonnull)activationID enabledVitalSigns:(BIOVitalSignType)enabledVitalSigns externalSensorEnabledVitalSigns:(BIOVitalSignType)externalSensorEnabledVitalSigns totalOfflineMeasurements:(int64_t)totalOfflineMeasurements remainingOfflineMeasurements:(int64_t)remainingOfflineMeasurements offlineMeasurementEndTimestamp:(int64_t)offlineMeasurementEndTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BIOLogsLevel;

/// Defines the configuration used for log collection during a session.
/// Use this class to specify the desired log level and whether logs should be saved
/// in a publicly accessible folder.
/// <ul>
///   <li>
///     <code>level</code>: Represents the types of logs that should be collected. Use one of the
///     predefined levels such as <code>LogsLevel.default</code>.
///   </li>
///   <li>
///     <code>saveToPublicFolder</code>: When set to <code>true</code>, logs will be saved to the app’s Documents
///     directory, making them accessible to the user via the Files app.
///   </li>
/// </ul>
/// <blockquote>
/// Note: If <code>saveToPublicFolder</code> is <code>true</code>, it is recommended to add the following keys to your Info.plist:
///
/// </blockquote>
/// <ul>
///   <li>
///     <code>UIFileSharingEnabled</code> = YES
///   </li>
///   <li>
///     <code>LSSupportsOpeningDocumentsInPlace</code> = YES
///   </li>
/// </ul>
/// <h3>Example:</h3>
/// \code
/// let config = LogsConfiguration(
///     level: .default,
///     saveToPublicFolder: true
/// )
///
/// \endcode
SWIFT_CLASS_NAMED("LogsConfiguration")
@interface BIOLogsConfiguration : NSObject
@property (nonatomic, readonly, strong) BIOLogsLevel * _Nonnull level;
@property (nonatomic, readonly) BOOL saveToPublicFolder;
- (nonnull instancetype)initWithLevel:(BIOLogsLevel * _Nonnull)level saveToPublicFolder:(BOOL)saveToPublicFolder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("LogsInfo")
@interface BIOLogsInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull logsPath;
@property (nonatomic, readonly) NSInteger measurementDuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents the logs level configuration used in the SDK, defining which types of logs are enabled during a session.
/// Use one of the predefined levels, such as <code>LogsLevel.default</code>, to control which types of logs
/// are included during the session.
/// <blockquote>
/// Important: Do <em>not</em> initialize <code>LogsLevel</code> using <code>init(...)</code> directly. Always use the
/// provided predefined levels.
///
/// </blockquote>
/// <h3>Example:</h3>
/// \code
/// // Use the default log level
/// let level = LogsLevel.default
///
/// \endcode
SWIFT_CLASS_NAMED("LogsLevel")
@interface BIOLogsLevel : NSObject
@property (nonatomic, readonly) NSInteger rawValue;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) BIOLogsLevel * _Nonnull default_;)
+ (BIOLogsLevel * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("LogsListener")
@protocol BIOLogsListener
- (void)onLogsReadyWithLogsInfo:(BIOLogsInfo * _Nonnull)logsInfo;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOLowHemoglobinRisk, "LowHemoglobinRisk", open) {
  BIOLowHemoglobinRiskUnknown = 0,
  BIOLowHemoglobinRiskLow = 1,
  BIOLowHemoglobinRiskMedium = 2,
  BIOLowHemoglobinRiskHigh = 3,
};


SWIFT_CLASS_NAMED("MeasurementInfo")
@interface BIOMeasurementInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable measurementFolderName;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionFolderPath;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOPnsZone, "PNSZone", open) {
  BIOPnsZoneUnknown = 0,
  BIOPnsZoneLow = 1,
  BIOPnsZoneNormal = 2,
  BIOPnsZoneHigh = 3,
};


SWIFT_CLASS_NAMED("PPGData")
@interface BIOPpgData : NSObject
@property (nonatomic, readonly) double timestamp;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull ppgValues;
@property (nonatomic, readonly) double ambient;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum BIOPpgDeviceType : NSInteger;

SWIFT_CLASS_NAMED("PPGDevice")
@interface BIOPpgDevice : NSObject
@property (nonatomic, readonly) enum BIOPpgDeviceType type;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceID;
- (nonnull instancetype)initWithType:(enum BIOPpgDeviceType)type deviceID:(NSString * _Nonnull)deviceID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PPGDeviceInfo")
@interface BIOPpgDeviceInfo : NSObject
@property (nonatomic, readonly) enum BIOPpgDeviceType type;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceID;
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
- (nonnull instancetype)initWithType:(enum BIOPpgDeviceType)type deviceID:(NSString * _Nonnull)deviceID version:(NSString * _Nonnull)version OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL_NAMED("PPGDeviceInfoListener")
@protocol BIOPpgDeviceInfoListener
- (void)onPPGDeviceBatteryLevel:(NSUInteger)batteryLevel;
- (void)onPPGDeviceInfo:(BIOPpgDeviceInfo * _Nonnull)info;
@end


SWIFT_PROTOCOL_NAMED("PPGDeviceScanner")
@protocol BIOPpgDeviceScanner
- (BOOL)startAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)startWithTimeout:(NSUInteger)timeout error:(NSError * _Nullable * _Nullable)error;
- (void)stop;
@end

@protocol BIOPpgDeviceScannerListener;

SWIFT_CLASS_NAMED("PPGDeviceScannerFactory")
@interface BIOPpgDeviceScannerFactory : NSObject
+ (id <BIOPpgDeviceScanner> _Nullable)createWithPpgDeviceType:(enum BIOPpgDeviceType)ppgDeviceType listener:(id <BIOPpgDeviceScannerListener> _Nonnull)listener error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL_NAMED("PPGDeviceScannerListener")
@protocol BIOPpgDeviceScannerListener
- (void)onPPGDeviceDiscoveredWithPpgDevice:(BIOPpgDevice * _Nonnull)ppgDevice;
- (void)onPPGDeviceScanFinished;
@end


SWIFT_CLASS_NAMED("PPGDeviceSessionBuilder")
@interface BIOPpgDeviceSessionBuilder : NSObject
@property (nonatomic, readonly, weak) id <BIOSessionInfoListener> _Nullable sessionInfoListener;
@property (nonatomic, readonly, weak) id <BIOVitalSignsListener> _Nullable vitalSignsListener;
@property (nonatomic, readonly, weak) id <BIOPpgDeviceInfoListener> _Nullable ppgDeviceInfoListener;
@property (nonatomic, readonly, weak) id <BIOFallDetectionListener> _Nullable fallDetectionListener;
@property (nonatomic, readonly, weak) id <BIOLogsListener> _Nullable logsListener;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable options;
@property (nonatomic, readonly, strong) BIOLicenseDetails * _Nonnull licenseDetails;
@property (nonatomic, readonly) BOOL analyticsEnabled;
@property (nonatomic, readonly, strong) BIOLogsConfiguration * _Nullable logsConfiguration;
- (id <BIOSession> _Nullable)buildWithLicenseDetails:(BIOLicenseDetails * _Nonnull)licenseDetails error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BIOPpgDeviceSessionBuilder * _Nonnull)withSessionInfoListener:(id <BIOSessionInfoListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (BIOPpgDeviceSessionBuilder * _Nonnull)withVitalSignsListener:(id <BIOVitalSignsListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (BIOPpgDeviceSessionBuilder * _Nonnull)withPPGDeviceInfoListener:(id <BIOPpgDeviceInfoListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (BIOPpgDeviceSessionBuilder * _Nonnull)withOptionsWithOptions:(NSDictionary<NSString *, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BIOPpgDeviceSessionBuilder * _Nonnull)withAnalytics SWIFT_WARN_UNUSED_RESULT;
- (BIOPpgDeviceSessionBuilder * _Nonnull)withLogsConfiguration:(BIOLogsConfiguration * _Nonnull)configuration listener:(id <BIOLogsListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOPpgDeviceType, "PPGDeviceType", open) {
  BIOPpgDeviceTypePolar = 0,
};


SWIFT_CLASS_NAMED("PolarSessionBuilder")
@interface BIOPolarSessionBuilder : BIOPpgDeviceSessionBuilder
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull polarMinVersion;)
+ (NSString * _Nonnull)polarMinVersion SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull polarDeviceID;
@property (nonatomic, readonly, strong) BIOUserInformation * _Nullable userInformation;
- (nonnull instancetype)initWithPolarDeviceID:(NSString * _Nonnull)polarDeviceID OBJC_DESIGNATED_INITIALIZER;
- (BIOPolarSessionBuilder * _Nonnull)withSubjectDemographic:(BIOSubjectDemographic * _Nonnull)demographic SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use `withUserInformation()` instead.");
- (BIOPolarSessionBuilder * _Nonnull)withUserInformation:(BIOUserInformation * _Nonnull)userInformation SWIFT_WARN_UNUSED_RESULT;
- (BIOPolarSessionBuilder * _Nonnull)withFallDetectionListener:(id <BIOFallDetectionListener> _Nullable)listener SWIFT_WARN_UNUSED_RESULT;
- (id <BIOSession> _Nullable)buildWithLicenseDetails:(BIOLicenseDetails * _Nonnull)licenseDetails error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("RRI")
@interface BIORRI : NSObject
@property (nonatomic, readonly) double timestamp;
@property (nonatomic, readonly) NSInteger interval;
- (nonnull instancetype)initWithTimestamp:(double)timestamp interval:(NSInteger)interval OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOSnsZone, "SNSZone", open) {
  BIOSnsZoneUnknown = 0,
  BIOSnsZoneLow = 1,
  BIOSnsZoneNormal = 2,
  BIOSnsZoneHigh = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOSensorSourceType, "SensorSourceType", open) {
  BIOSensorSourceTypeInternal = 0,
  BIOSensorSourceTypePolar = 1,
};

enum BIOSessionState : NSInteger;

SWIFT_PROTOCOL_NAMED("Session")
@protocol BIOSession
- (BOOL)startWithMeasurementDuration:(uint64_t)measurementDuration error:(NSError * _Nullable * _Nullable)error;
- (BOOL)stopAndReturnError:(NSError * _Nullable * _Nullable)error;
- (void)terminate;
@property (nonatomic, readonly) enum BIOSessionState state;
@end



SWIFT_CLASS_NAMED("SessionEnabledVitalSigns")
@interface BIOSessionEnabledVitalSigns : NSObject
@property (nonatomic, readonly, strong) BIOEnabledVitalSigns * _Nonnull deviceEnabled;
@property (nonatomic, readonly, strong) BIOEnabledVitalSigns * _Nonnull measurementModeEnabled;
@property (nonatomic, readonly, strong) BIOEnabledVitalSigns * _Nonnull licenseEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDeviceEnabled:(BIOEnabledVitalSigns * _Nonnull)deviceEnabled measurementModeEnabled:(BIOEnabledVitalSigns * _Nonnull)measurementModeEnabled licenseEnabled:(BIOEnabledVitalSigns * _Nonnull)licenseEnabled OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEnabledWithVitalSignType:(BIOVitalSignType)vitalSignType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isDeviceEnabledWithVitalSignType:(BIOVitalSignType)vitalSignType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isMeasurementModeEnabledWithVitalSignType:(BIOVitalSignType)vitalSignType SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isLicenseEnabledWithVitalSignType:(BIOVitalSignType)vitalSignType SWIFT_WARN_UNUSED_RESULT;
@end

@class BIOWarningData;

SWIFT_PROTOCOL_NAMED("SessionInfoListener")
@protocol BIOSessionInfoListener
- (void)onSessionStateChangeWithSessionState:(enum BIOSessionState)sessionState;
- (void)onWarningWithWarningData:(BIOWarningData * _Nonnull)warningData;
- (void)onErrorWithErrorData:(BIOErrorData * _Nonnull)errorData;
- (void)onLicenseInfoWithLicenseInfo:(BIOLicenseInfo * _Nonnull)licenseInfo;
- (void)onEnabledVitalSignsWithEnabledVitalSigns:(BIOSessionEnabledVitalSigns * _Nonnull)enabledVitalSigns;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOSessionState, "SessionState", open) {
  BIOSessionStateInitializing = 0,
  BIOSessionStateReady = 1,
  BIOSessionStateStarting = 2,
  BIOSessionStateProcessing = 3,
  BIOSessionStateStopping = 4,
  BIOSessionStateTerminating = 5,
  BIOSessionStateTerminated = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOSex, "Sex", open) {
  BIOSexUnspecified = 0,
  BIOSexMale = 1,
  BIOSexFemale = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOSmokingStatus, "SmokingStatus", open) {
  BIOSmokingStatusUnspecified = 0,
  BIOSmokingStatusSmoker = 1,
  BIOSmokingStatusNonSmoker = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, BIOStressLevel, "StressLevel", open) {
  BIOStressLevelUnknown = 0,
  BIOStressLevelLow = 1,
  BIOStressLevelNormal = 2,
  BIOStressLevelMild = 3,
  BIOStressLevelHigh = 4,
  BIOStressLevelExtreme = 5,
};

@class NSNumber;

SWIFT_CLASS_NAMED("SubjectDemographic") SWIFT_DEPRECATED_MSG("Use `UserInformation` instead.")
@interface BIOSubjectDemographic : NSObject
@property (nonatomic, readonly) enum BIOSex sex;
@property (nonatomic, readonly, strong) NSNumber * _Nullable age;
@property (nonatomic, readonly, strong) NSNumber * _Nullable weight;
@property (nonatomic, readonly, strong) NSNumber * _Nullable height;
- (nonnull instancetype)initWithSex:(enum BIOSex)sex age:(NSNumber * _Nullable)age weight:(NSNumber * _Nullable)weight OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED;
- (nonnull instancetype)initWithSex:(enum BIOSex)sex age:(NSNumber * _Nullable)age weight:(NSNumber * _Nullable)weight height:(NSNumber * _Nullable)height OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class representing subject information such as sex, age, weight, height, and smoking status.
/// To create an instance of this class, use <code>UserInformationBuilder</code>.
/// The builder allows you to set each property in a chainable manner and then call <code>build()</code> to create the object.
/// Example usage:
/// \code
/// let subjectInfo = UserInformationBuilder()
///     .setSex(.female)
///     .setAge(35)
///     .setWeight(65)
///     .setHeight(160)
///     .setSmokingStatus(.nonSmoker)
///     .build()
///
/// \endcode\param sex The subject’s sex.
///
/// \param age The subject’s age in years (optional).
///
/// \param weight The subject’s weight in kilograms (optional).
///
/// \param height The subject’s height in centimeters (optional).
///
/// \param smokingStatus The subject’s smoking status.
///
SWIFT_CLASS_NAMED("UserInformation")
@interface BIOUserInformation : NSObject
@property (nonatomic, readonly) enum BIOSex sex;
@property (nonatomic, readonly, strong) NSNumber * _Nullable age;
@property (nonatomic, readonly, strong) NSNumber * _Nullable weight;
@property (nonatomic, readonly, strong) NSNumber * _Nullable height;
@property (nonatomic, readonly) enum BIOSmokingStatus smokingStatus;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("UserInformationBuilder")
@interface BIOUserInformationBuilder : NSObject
@property (nonatomic, readonly) enum BIOSex _sex;
@property (nonatomic, readonly, strong) NSNumber * _Nullable _age;
@property (nonatomic, readonly, strong) NSNumber * _Nullable _weight;
@property (nonatomic, readonly, strong) NSNumber * _Nullable _height;
@property (nonatomic, readonly) enum BIOSmokingStatus _smokingStatus;
- (BIOUserInformationBuilder * _Nonnull)setSex:(enum BIOSex)sex SWIFT_WARN_UNUSED_RESULT;
- (BIOUserInformationBuilder * _Nonnull)setAge:(NSNumber * _Nonnull)age SWIFT_WARN_UNUSED_RESULT;
- (BIOUserInformationBuilder * _Nonnull)setWeight:(NSNumber * _Nonnull)weight SWIFT_WARN_UNUSED_RESULT;
- (BIOUserInformationBuilder * _Nonnull)setHeight:(NSNumber * _Nonnull)height SWIFT_WARN_UNUSED_RESULT;
- (BIOUserInformationBuilder * _Nonnull)setSmokingStatus:(enum BIOSmokingStatus)smokingStatus SWIFT_WARN_UNUSED_RESULT;
- (BIOUserInformation * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL_NAMED("VitalSign")
@protocol BIOVitalSign
@property (nonatomic, readonly) BIOVitalSignType type;
@end


SWIFT_CLASS_NAMED("VitalSignDouble")
@interface BIOVitalSignDouble : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) double value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignASCVDRisk")
@interface BIOVitalSignAscvdRidk : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignASCVDRiskLevel")
@interface BIOVitalSignASCVDRiskLevel : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOASCVDRiskLevel value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignBloodPressure")
@interface BIOVitalSignBloodPressure : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly, strong) BIOBloodPressure * _Nonnull value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOVitalSignBloodPressure (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignInt")
@interface BIOVitalSignInt : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) NSInteger value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignBodyTensionScore")
@interface BIOVitalSignBodyTensionScore : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignCardiacWorkload")
@interface BIOVitalSignCardiacWorkload : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignConfidence")
@interface BIOVitalSignConfidence : NSObject
@property (nonatomic, readonly) enum BIOConfidenceLevel level;
- (nonnull instancetype)initWithLevel:(enum BIOConfidenceLevel)level OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface BIOVitalSignDouble (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignHeartAge")
@interface BIOVitalSignHeartAge : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignHemoglobin")
@interface BIOVitalSignHemoglobin : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignHemoglobinA1C")
@interface BIOVitalSignHemoglobinA1C : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignHighBloodPressureRisk")
@interface BIOVitalSignHighBloodPressureRisk : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOHighBloodPressureRisk value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignHighFastingGlucoseRisk")
@interface BIOVitalSignHighFastingGlucoseRisk : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOHighFastingGlucoseRisk value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignHighHemoglobinA1CRisk")
@interface BIOVitalSignHighHemoglobinA1CRisk : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOHighHemoglobinA1CRisk value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignHighTotalCholesterolRisk")
@interface BIOVitalSignHighTotalCholesterolRisk : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOHighTotalCholesterolRisk value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface BIOVitalSignInt (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignLFHF")
@interface BIOVitalSignLFHF : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignLowHemoglobinRisk")
@interface BIOVitalSignLowHemoglobinRisk : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOLowHemoglobinRisk value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("VitalSignMeanArterialPressure")
@interface BIOVitalSignMeanArterialPressure : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignMeanRRI")
@interface BIOVitalSignMeanRRI : BIOVitalSignInt
@property (nonatomic, readonly, strong) BIOVitalSignConfidence * _Nullable confidence;
@end


SWIFT_CLASS_NAMED("VitalSignNormalizedStressIndex")
@interface BIOVitalSignNormalizedStressIndex : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignOxygenSaturation")
@interface BIOVitalSignOxygenSaturation : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignPNSIndex")
@interface BIOVitalSignPNSIndex : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignPNSZone")
@interface BIOVitalSignPNSZone : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOPnsZone value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOVitalSignPNSZone (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignPRQ")
@interface BIOVitalSignPRQ : BIOVitalSignDouble
@property (nonatomic, readonly, strong) BIOVitalSignConfidence * _Nullable confidence;
@end


SWIFT_CLASS_NAMED("VitalSignPulsePressure")
@interface BIOVitalSignPulsePressure : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignPulseRate")
@interface BIOVitalSignPulseRate : BIOVitalSignInt
@property (nonatomic, readonly, strong) BIOVitalSignConfidence * _Nullable confidence;
@end


SWIFT_CLASS_NAMED("VitalSignRMSSD")
@interface BIOVitalSignRMSSD : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignRRI")
@interface BIOVitalSignRRI : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly, copy) NSArray<BIORRI *> * _Nonnull value;
@property (nonatomic, readonly, strong) BIOVitalSignConfidence * _Nullable confidence;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOVitalSignRRI (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignRespirationRate")
@interface BIOVitalSignRespirationRate : BIOVitalSignInt
@property (nonatomic, readonly, strong) BIOVitalSignConfidence * _Nullable confidence;
@end


SWIFT_CLASS_NAMED("VitalSignSD1")
@interface BIOVitalSignSD1 : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignSD2")
@interface BIOVitalSignSD2 : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignSDNN")
@interface BIOVitalSignSDNN : BIOVitalSignInt
@property (nonatomic, readonly, strong) BIOVitalSignConfidence * _Nullable confidence;
@end


SWIFT_CLASS_NAMED("VitalSignSNSIndex")
@interface BIOVitalSignSNSIndex : BIOVitalSignDouble
@end


SWIFT_CLASS_NAMED("VitalSignSNSZone")
@interface BIOVitalSignSNSZone : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOSnsZone value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOVitalSignSNSZone (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignStressIndex")
@interface BIOVitalSignStressIndex : BIOVitalSignInt
@end


SWIFT_CLASS_NAMED("VitalSignStressLevel")
@interface BIOVitalSignStressLevel : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOStressLevel value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOVitalSignStressLevel (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end


SWIFT_CLASS_NAMED("VitalSignTypes")
@interface BIOVitalSignTypes : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType none;)
+ (BIOVitalSignType)none SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType pulseRate;)
+ (BIOVitalSignType)pulseRate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType respirationRate;)
+ (BIOVitalSignType)respirationRate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType oxygenSaturation;)
+ (BIOVitalSignType)oxygenSaturation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType stressLevel;)
+ (BIOVitalSignType)stressLevel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType stressIndex;)
+ (BIOVitalSignType)stressIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType sdnn;)
+ (BIOVitalSignType)sdnn SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType bloodPressure;)
+ (BIOVitalSignType)bloodPressure SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType rri;)
+ (BIOVitalSignType)rri SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType meanRri;)
+ (BIOVitalSignType)meanRri SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType rmssd;)
+ (BIOVitalSignType)rmssd SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType sd1;)
+ (BIOVitalSignType)sd1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType sd2;)
+ (BIOVitalSignType)sd2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType prq;)
+ (BIOVitalSignType)prq SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType pnsIndex;)
+ (BIOVitalSignType)pnsIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType pnsZone;)
+ (BIOVitalSignType)pnsZone SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType snsIndex;)
+ (BIOVitalSignType)snsIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType snsZone;)
+ (BIOVitalSignType)snsZone SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType wellnessIndex;)
+ (BIOVitalSignType)wellnessIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType wellnessLevel;)
+ (BIOVitalSignType)wellnessLevel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType lfhf;)
+ (BIOVitalSignType)lfhf SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType hemoglobin;)
+ (BIOVitalSignType)hemoglobin SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType hemoglobinA1C;)
+ (BIOVitalSignType)hemoglobinA1C SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType highHemoglobinA1CRisk;)
+ (BIOVitalSignType)highHemoglobinA1CRisk SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType highBloodPressureRisk;)
+ (BIOVitalSignType)highBloodPressureRisk SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType ascvdRisk;)
+ (BIOVitalSignType)ascvdRisk SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType normalizedStressIndex;)
+ (BIOVitalSignType)normalizedStressIndex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType heartAge;)
+ (BIOVitalSignType)heartAge SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType lowHemoglobinRisk;)
+ (BIOVitalSignType)lowHemoglobinRisk SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType highTotalCholesterolRisk;)
+ (BIOVitalSignType)highTotalCholesterolRisk SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType highFastingGlucoseRisk;)
+ (BIOVitalSignType)highFastingGlucoseRisk SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType cardiacWorkload;)
+ (BIOVitalSignType)cardiacWorkload SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType ascvdRiskLevel;)
+ (BIOVitalSignType)ascvdRiskLevel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType meanArterialPressure;)
+ (BIOVitalSignType)meanArterialPressure SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType pulsePressure;)
+ (BIOVitalSignType)pulsePressure SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BIOVitalSignType bodyTensionScore;)
+ (BIOVitalSignType)bodyTensionScore SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull all;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("VitalSignWellnessIndex")
@interface BIOVitalSignWellnessIndex : BIOVitalSignInt
@end

enum BIOWellnessLevel : NSInteger;

SWIFT_CLASS_NAMED("VitalSignWellnessLevel")
@interface BIOVitalSignWellnessLevel : NSObject <BIOVitalSign>
@property (nonatomic, readonly) BIOVitalSignType type;
@property (nonatomic, readonly) enum BIOWellnessLevel value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface BIOVitalSignWellnessLevel (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull bioDescription;
@end

@class BIOVitalSignsResults;

SWIFT_PROTOCOL_NAMED("VitalSignsListener")
@protocol BIOVitalSignsListener
- (void)onVitalSignWithVitalSign:(id <BIOVitalSign> _Nonnull)vitalSign;
- (void)onFinalResultsWithResults:(BIOVitalSignsResults * _Nonnull)results;
@end


SWIFT_CLASS_NAMED("VitalSignsResults")
@interface BIOVitalSignsResults : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSArray<id <BIOVitalSign>> * _Nonnull)getResults SWIFT_WARN_UNUSED_RESULT;
- (id <BIOVitalSign> _Nullable)getResultOf:(BIOVitalSignType)vitalSignType SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSNumber *> * _Nonnull)getVitalSignTypes SWIFT_WARN_UNUSED_RESULT;
@end


@interface BIOVitalSignsResults (SWIFT_EXTENSION(BiosenseSignal))
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS_NAMED("WarningData")
@interface BIOWarningData : NSObject <BIOAlertData>
@property (nonatomic, copy) NSString * _Nonnull domain;
@property (nonatomic) NSInteger code;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BIOWellnessLevel, "WellnessLevel", open) {
  BIOWellnessLevelUnknown = 0,
  BIOWellnessLevelLow = 1,
  BIOWellnessLevelMedium = 2,
  BIOWellnessLevelHigh = 3,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
